{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0fa21315-4980-4815-88e4-cb9721912ce9",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import requests\n",
    "import spotipy.util as util\n",
    "import spotipy\n",
    "from spotipy.oauth2 import SpotifyClientCredentials\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "cb04c674-0b4e-4f48-a792-658fdc0b76bc",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "# Get your client id, secret key, and redirect URI from your application https://developer.spotify.com/dashboard/applications\n",
    "client_id ='CLIENT ID' #<----------------- YOUR ID HERE\n",
    "    \n",
    "client_secret = \"CLIENT SECRET\" #<----------------- YOUR SECRET HERE\n",
    "username = 'USERNAME' #<----------------- YOUR USERNAME HERE\n",
    "scope = 'SCOPE' #<------------- depends on your needs, you can select different scope https://developer.spotify.com/documentation/general/guides/scopes/\n",
    "redirect_uri = 'REDIRECT URL'#<----------------- PUT REDIRECT URI HERE"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "2762d9a4-d5de-48fb-97df-03db0fd9d5d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "from spotipy.oauth2 import SpotifyOAuth"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "e2d53538-c200-4af2-b1ac-33eb8aff0f7f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Authenticate and initialize Spotify client\n",
    "sp_oauth = SpotifyOAuth(client_id=client_id,\n",
    "                        client_secret=client_secret,\n",
    "                        redirect_uri=redirect_uri,\n",
    "                        scope=scope)\n",
    "\n",
    "# Get the access token (it returns a string directly if as_dict=False)\n",
    "token_info = sp_oauth.get_access_token(as_dict=True)  # default is as_dict=True\n",
    "\n",
    "# Initialize Spotify client with access token\n",
    "sp = spotipy.Spotify(auth=token_info['access_token'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "69b050a7-73db-48d6-af73-d1b35b913ace",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "artist you like: bts\n"
     ]
    }
   ],
   "source": [
    "artist=input(\"artist you like:\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "e471d765-e725-4025-a104-08b23d67648b",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'artists': {'href': 'https://api.spotify.com/v1/search?query=bts&type=artist&offset=0&limit=1', 'items': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Nrfpe0tUJi4K4DXYWgMUX'}, 'followers': {'href': None, 'total': 75733468}, 'genres': ['k-pop', 'k-pop boy group', 'pop'], 'href': 'https://api.spotify.com/v1/artists/3Nrfpe0tUJi4K4DXYWgMUX', 'id': '3Nrfpe0tUJi4K4DXYWgMUX', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebd642648235ebf3460d2d1f6a', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174d642648235ebf3460d2d1f6a', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178d642648235ebf3460d2d1f6a', 'width': 160}], 'name': 'BTS', 'popularity': 87, 'type': 'artist', 'uri': 'spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX'}], 'limit': 1, 'next': 'https://api.spotify.com/v1/search?query=bts&type=artist&offset=1&limit=1', 'offset': 0, 'previous': None, 'total': 100}}\n"
     ]
    }
   ],
   "source": [
    "# Search for the artist\n",
    "artist_info = sp.search(artist, limit=1, offset=0, type='artist', market=None)\n",
    "if not artist_info['artists']['items']:\n",
    "    print(\"Artist not found.\")\n",
    "else:\n",
    "    print(artist_info)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "315319c5-7afb-478e-8abe-27d2936537d6",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'3Nrfpe0tUJi4K4DXYWgMUX'"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "artist_info = artist_info['artists']['items'][0]\n",
    "artist_id = artist_info['id']\n",
    "artist_id"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "021af922-2bd7-4ea2-b7c2-960c34c04aaf",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>album_type</th>\n",
       "      <th>total_tracks</th>\n",
       "      <th>available_markets</th>\n",
       "      <th>external_urls</th>\n",
       "      <th>href</th>\n",
       "      <th>id</th>\n",
       "      <th>images</th>\n",
       "      <th>name</th>\n",
       "      <th>release_date</th>\n",
       "      <th>release_date_precision</th>\n",
       "      <th>type</th>\n",
       "      <th>uri</th>\n",
       "      <th>artists</th>\n",
       "      <th>album_group</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>album</td>\n",
       "      <td>35</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/album/6a...</td>\n",
       "      <td>https://api.spotify.com/v1/albums/6al2VdKbb6FI...</td>\n",
       "      <td>6al2VdKbb6FIz9d7lU7WRB</td>\n",
       "      <td>[{'url': 'https://i.scdn.co/image/ab67616d0000...</td>\n",
       "      <td>Proof</td>\n",
       "      <td>2022-06-10</td>\n",
       "      <td>day</td>\n",
       "      <td>album</td>\n",
       "      <td>spotify:album:6al2VdKbb6FIz9d7lU7WRB</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>album</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>album</td>\n",
       "      <td>8</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/album/6n...</td>\n",
       "      <td>https://api.spotify.com/v1/albums/6nYfHQnvkvOT...</td>\n",
       "      <td>6nYfHQnvkvOTNHnOhDT3sr</td>\n",
       "      <td>[{'url': 'https://i.scdn.co/image/ab67616d0000...</td>\n",
       "      <td>BE</td>\n",
       "      <td>2020-11-20</td>\n",
       "      <td>day</td>\n",
       "      <td>album</td>\n",
       "      <td>spotify:album:6nYfHQnvkvOTNHnOhDT3sr</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>album</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>album</td>\n",
       "      <td>13</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/album/1n...</td>\n",
       "      <td>https://api.spotify.com/v1/albums/1nScVw87kRJi...</td>\n",
       "      <td>1nScVw87kRJiT2bg2Kswhp</td>\n",
       "      <td>[{'url': 'https://i.scdn.co/image/ab67616d0000...</td>\n",
       "      <td>MAP OF THE SOUL : 7 ~ THE JOURNEY ~</td>\n",
       "      <td>2020-07-14</td>\n",
       "      <td>day</td>\n",
       "      <td>album</td>\n",
       "      <td>spotify:album:1nScVw87kRJiT2bg2Kswhp</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>album</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>album</td>\n",
       "      <td>20</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/album/5W...</td>\n",
       "      <td>https://api.spotify.com/v1/albums/5W1XY5ucNATj...</td>\n",
       "      <td>5W1XY5ucNATjTULERvXx9j</td>\n",
       "      <td>[{'url': 'https://i.scdn.co/image/ab67616d0000...</td>\n",
       "      <td>MAP OF THE SOUL : 7</td>\n",
       "      <td>2020-02-21</td>\n",
       "      <td>day</td>\n",
       "      <td>album</td>\n",
       "      <td>spotify:album:5W1XY5ucNATjTULERvXx9j</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>album</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>album</td>\n",
       "      <td>7</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/album/2K...</td>\n",
       "      <td>https://api.spotify.com/v1/albums/2KqlAl1Kl5fZ...</td>\n",
       "      <td>2KqlAl1Kl5fZvbFgJ0qFB6</td>\n",
       "      <td>[{'url': 'https://i.scdn.co/image/ab67616d0000...</td>\n",
       "      <td>MAP OF THE SOUL : PERSONA</td>\n",
       "      <td>2019-04-12</td>\n",
       "      <td>day</td>\n",
       "      <td>album</td>\n",
       "      <td>spotify:album:2KqlAl1Kl5fZvbFgJ0qFB6</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>album</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  album_type  total_tracks                                  available_markets  \\\n",
       "0      album            35  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...   \n",
       "1      album             8  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...   \n",
       "2      album            13  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...   \n",
       "3      album            20  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...   \n",
       "4      album             7  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...   \n",
       "\n",
       "                                       external_urls  \\\n",
       "0  {'spotify': 'https://open.spotify.com/album/6a...   \n",
       "1  {'spotify': 'https://open.spotify.com/album/6n...   \n",
       "2  {'spotify': 'https://open.spotify.com/album/1n...   \n",
       "3  {'spotify': 'https://open.spotify.com/album/5W...   \n",
       "4  {'spotify': 'https://open.spotify.com/album/2K...   \n",
       "\n",
       "                                                href                      id  \\\n",
       "0  https://api.spotify.com/v1/albums/6al2VdKbb6FI...  6al2VdKbb6FIz9d7lU7WRB   \n",
       "1  https://api.spotify.com/v1/albums/6nYfHQnvkvOT...  6nYfHQnvkvOTNHnOhDT3sr   \n",
       "2  https://api.spotify.com/v1/albums/1nScVw87kRJi...  1nScVw87kRJiT2bg2Kswhp   \n",
       "3  https://api.spotify.com/v1/albums/5W1XY5ucNATj...  5W1XY5ucNATjTULERvXx9j   \n",
       "4  https://api.spotify.com/v1/albums/2KqlAl1Kl5fZ...  2KqlAl1Kl5fZvbFgJ0qFB6   \n",
       "\n",
       "                                              images  \\\n",
       "0  [{'url': 'https://i.scdn.co/image/ab67616d0000...   \n",
       "1  [{'url': 'https://i.scdn.co/image/ab67616d0000...   \n",
       "2  [{'url': 'https://i.scdn.co/image/ab67616d0000...   \n",
       "3  [{'url': 'https://i.scdn.co/image/ab67616d0000...   \n",
       "4  [{'url': 'https://i.scdn.co/image/ab67616d0000...   \n",
       "\n",
       "                                  name release_date release_date_precision  \\\n",
       "0                                Proof   2022-06-10                    day   \n",
       "1                                   BE   2020-11-20                    day   \n",
       "2  MAP OF THE SOUL : 7 ~ THE JOURNEY ~   2020-07-14                    day   \n",
       "3                  MAP OF THE SOUL : 7   2020-02-21                    day   \n",
       "4            MAP OF THE SOUL : PERSONA   2019-04-12                    day   \n",
       "\n",
       "    type                                   uri  \\\n",
       "0  album  spotify:album:6al2VdKbb6FIz9d7lU7WRB   \n",
       "1  album  spotify:album:6nYfHQnvkvOTNHnOhDT3sr   \n",
       "2  album  spotify:album:1nScVw87kRJiT2bg2Kswhp   \n",
       "3  album  spotify:album:5W1XY5ucNATjTULERvXx9j   \n",
       "4  album  spotify:album:2KqlAl1Kl5fZvbFgJ0qFB6   \n",
       "\n",
       "                                             artists album_group  \n",
       "0  [{'external_urls': {'spotify': 'https://open.s...       album  \n",
       "1  [{'external_urls': {'spotify': 'https://open.s...       album  \n",
       "2  [{'external_urls': {'spotify': 'https://open.s...       album  \n",
       "3  [{'external_urls': {'spotify': 'https://open.s...       album  \n",
       "4  [{'external_urls': {'spotify': 'https://open.s...       album  "
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Get albums by the artist\n",
    "albums = sp.artist_albums(artist_id, album_type=[\"album\", \"single\", \"appears_on\"], limit=50)\n",
    "albums_df = pd.DataFrame(albums['items'])\n",
    "albums_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "dc654b98-8b0d-4a2b-ab16-0d39bc8c5e42",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>artists</th>\n",
       "      <th>available_markets</th>\n",
       "      <th>disc_number</th>\n",
       "      <th>duration_ms</th>\n",
       "      <th>explicit</th>\n",
       "      <th>external_urls</th>\n",
       "      <th>href</th>\n",
       "      <th>id</th>\n",
       "      <th>name</th>\n",
       "      <th>preview_url</th>\n",
       "      <th>track_number</th>\n",
       "      <th>type</th>\n",
       "      <th>uri</th>\n",
       "      <th>is_local</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>238628</td>\n",
       "      <td>False</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/1I...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/1IthE5GNiRzF...</td>\n",
       "      <td>1IthE5GNiRzFN5CVaCa445</td>\n",
       "      <td>Born Singer</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/ed6b39048436eed9...</td>\n",
       "      <td>1</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:1IthE5GNiRzFN5CVaCa445</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>222066</td>\n",
       "      <td>False</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/27...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/27S8iOXD7Z58...</td>\n",
       "      <td>27S8iOXD7Z58yvJtyk2S9j</td>\n",
       "      <td>No More Dream</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/57660681261bd993...</td>\n",
       "      <td>2</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:27S8iOXD7Z58yvJtyk2S9j</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>209751</td>\n",
       "      <td>False</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/2G...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/2GEnvQgSJhed...</td>\n",
       "      <td>2GEnvQgSJhedm2sqZlOP8o</td>\n",
       "      <td>N.O</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/fb5d285eb734057e...</td>\n",
       "      <td>3</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:2GEnvQgSJhedm2sqZlOP8o</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>231384</td>\n",
       "      <td>False</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/0v...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/0vMk4IrUfSJQ...</td>\n",
       "      <td>0vMk4IrUfSJQkhwZnVX6us</td>\n",
       "      <td>Boy In Luv</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/fa7c36a5b5248d48...</td>\n",
       "      <td>4</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:0vMk4IrUfSJQkhwZnVX6us</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>245810</td>\n",
       "      <td>False</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/0Q...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/0Q53fuiKLGjD...</td>\n",
       "      <td>0Q53fuiKLGjDKD7Mme7EoQ</td>\n",
       "      <td>Danger</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/93246e06867e64cc...</td>\n",
       "      <td>5</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:0Q53fuiKLGjDKD7Mme7EoQ</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                             artists  \\\n",
       "0  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "1  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "2  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "3  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "4  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "\n",
       "                                   available_markets  disc_number  \\\n",
       "0  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "1  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "2  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "3  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "4  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "\n",
       "   duration_ms  explicit                                      external_urls  \\\n",
       "0       238628     False  {'spotify': 'https://open.spotify.com/track/1I...   \n",
       "1       222066     False  {'spotify': 'https://open.spotify.com/track/27...   \n",
       "2       209751     False  {'spotify': 'https://open.spotify.com/track/2G...   \n",
       "3       231384     False  {'spotify': 'https://open.spotify.com/track/0v...   \n",
       "4       245810     False  {'spotify': 'https://open.spotify.com/track/0Q...   \n",
       "\n",
       "                                                href                      id  \\\n",
       "0  https://api.spotify.com/v1/tracks/1IthE5GNiRzF...  1IthE5GNiRzFN5CVaCa445   \n",
       "1  https://api.spotify.com/v1/tracks/27S8iOXD7Z58...  27S8iOXD7Z58yvJtyk2S9j   \n",
       "2  https://api.spotify.com/v1/tracks/2GEnvQgSJhed...  2GEnvQgSJhedm2sqZlOP8o   \n",
       "3  https://api.spotify.com/v1/tracks/0vMk4IrUfSJQ...  0vMk4IrUfSJQkhwZnVX6us   \n",
       "4  https://api.spotify.com/v1/tracks/0Q53fuiKLGjD...  0Q53fuiKLGjDKD7Mme7EoQ   \n",
       "\n",
       "            name                                        preview_url  \\\n",
       "0    Born Singer  https://p.scdn.co/mp3-preview/ed6b39048436eed9...   \n",
       "1  No More Dream  https://p.scdn.co/mp3-preview/57660681261bd993...   \n",
       "2            N.O  https://p.scdn.co/mp3-preview/fb5d285eb734057e...   \n",
       "3     Boy In Luv  https://p.scdn.co/mp3-preview/fa7c36a5b5248d48...   \n",
       "4         Danger  https://p.scdn.co/mp3-preview/93246e06867e64cc...   \n",
       "\n",
       "   track_number   type                                   uri  is_local  \n",
       "0             1  track  spotify:track:1IthE5GNiRzFN5CVaCa445     False  \n",
       "1             2  track  spotify:track:27S8iOXD7Z58yvJtyk2S9j     False  \n",
       "2             3  track  spotify:track:2GEnvQgSJhedm2sqZlOP8o     False  \n",
       "3             4  track  spotify:track:0vMk4IrUfSJQkhwZnVX6us     False  \n",
       "4             5  track  spotify:track:0Q53fuiKLGjDKD7Mme7EoQ     False  "
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "tracks_df = pd.DataFrame()\n",
    "    \n",
    "if not albums_df.empty:\n",
    "    for album_id in albums_df['id']:\n",
    "        album_tracks = sp.album_tracks(album_id, limit=50, offset=0, market=None)\n",
    "        tracks_df = pd.concat([tracks_df, pd.DataFrame(album_tracks['items'])])\n",
    "else:\n",
    "    print(\"Nothing found\")\n",
    "        \n",
    "tracks_df = tracks_df.reset_index(drop=True)  \n",
    "tracks_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "276a3498-555e-4593-98ef-4e808746e8a4",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>danceability</th>\n",
       "      <th>energy</th>\n",
       "      <th>key</th>\n",
       "      <th>loudness</th>\n",
       "      <th>mode</th>\n",
       "      <th>speechiness</th>\n",
       "      <th>acousticness</th>\n",
       "      <th>instrumentalness</th>\n",
       "      <th>liveness</th>\n",
       "      <th>valence</th>\n",
       "      <th>tempo</th>\n",
       "      <th>type</th>\n",
       "      <th>id</th>\n",
       "      <th>uri</th>\n",
       "      <th>track_href</th>\n",
       "      <th>analysis_url</th>\n",
       "      <th>duration_ms</th>\n",
       "      <th>time_signature</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0.602</td>\n",
       "      <td>0.841</td>\n",
       "      <td>8</td>\n",
       "      <td>-3.334</td>\n",
       "      <td>0</td>\n",
       "      <td>0.109</td>\n",
       "      <td>0.035400</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.235</td>\n",
       "      <td>0.684</td>\n",
       "      <td>157.937</td>\n",
       "      <td>audio_features</td>\n",
       "      <td>1IthE5GNiRzFN5CVaCa445</td>\n",
       "      <td>spotify:track:1IthE5GNiRzFN5CVaCa445</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/1IthE5GNiRzF...</td>\n",
       "      <td>https://api.spotify.com/v1/audio-analysis/1Ith...</td>\n",
       "      <td>238628</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>0.438</td>\n",
       "      <td>0.864</td>\n",
       "      <td>2</td>\n",
       "      <td>-5.185</td>\n",
       "      <td>1</td>\n",
       "      <td>0.470</td>\n",
       "      <td>0.011800</td>\n",
       "      <td>0.000002</td>\n",
       "      <td>0.431</td>\n",
       "      <td>0.594</td>\n",
       "      <td>167.898</td>\n",
       "      <td>audio_features</td>\n",
       "      <td>27S8iOXD7Z58yvJtyk2S9j</td>\n",
       "      <td>spotify:track:27S8iOXD7Z58yvJtyk2S9j</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/27S8iOXD7Z58...</td>\n",
       "      <td>https://api.spotify.com/v1/audio-analysis/27S8...</td>\n",
       "      <td>222067</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>0.597</td>\n",
       "      <td>0.909</td>\n",
       "      <td>11</td>\n",
       "      <td>-4.500</td>\n",
       "      <td>0</td>\n",
       "      <td>0.160</td>\n",
       "      <td>0.044300</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.374</td>\n",
       "      <td>0.564</td>\n",
       "      <td>146.870</td>\n",
       "      <td>audio_features</td>\n",
       "      <td>2GEnvQgSJhedm2sqZlOP8o</td>\n",
       "      <td>spotify:track:2GEnvQgSJhedm2sqZlOP8o</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/2GEnvQgSJhed...</td>\n",
       "      <td>https://api.spotify.com/v1/audio-analysis/2GEn...</td>\n",
       "      <td>209752</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>0.492</td>\n",
       "      <td>0.931</td>\n",
       "      <td>9</td>\n",
       "      <td>-3.837</td>\n",
       "      <td>0</td>\n",
       "      <td>0.297</td>\n",
       "      <td>0.002440</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.353</td>\n",
       "      <td>0.444</td>\n",
       "      <td>166.071</td>\n",
       "      <td>audio_features</td>\n",
       "      <td>0vMk4IrUfSJQkhwZnVX6us</td>\n",
       "      <td>spotify:track:0vMk4IrUfSJQkhwZnVX6us</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/0vMk4IrUfSJQ...</td>\n",
       "      <td>https://api.spotify.com/v1/audio-analysis/0vMk...</td>\n",
       "      <td>231384</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0.734</td>\n",
       "      <td>0.848</td>\n",
       "      <td>1</td>\n",
       "      <td>-4.433</td>\n",
       "      <td>1</td>\n",
       "      <td>0.102</td>\n",
       "      <td>0.000913</td>\n",
       "      <td>0.000247</td>\n",
       "      <td>0.256</td>\n",
       "      <td>0.370</td>\n",
       "      <td>112.021</td>\n",
       "      <td>audio_features</td>\n",
       "      <td>0Q53fuiKLGjDKD7Mme7EoQ</td>\n",
       "      <td>spotify:track:0Q53fuiKLGjDKD7Mme7EoQ</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/0Q53fuiKLGjD...</td>\n",
       "      <td>https://api.spotify.com/v1/audio-analysis/0Q53...</td>\n",
       "      <td>245810</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   danceability  energy  key  loudness  mode  speechiness  acousticness  \\\n",
       "0         0.602   0.841    8    -3.334     0        0.109      0.035400   \n",
       "1         0.438   0.864    2    -5.185     1        0.470      0.011800   \n",
       "2         0.597   0.909   11    -4.500     0        0.160      0.044300   \n",
       "3         0.492   0.931    9    -3.837     0        0.297      0.002440   \n",
       "4         0.734   0.848    1    -4.433     1        0.102      0.000913   \n",
       "\n",
       "   instrumentalness  liveness  valence    tempo            type  \\\n",
       "0          0.000000     0.235    0.684  157.937  audio_features   \n",
       "1          0.000002     0.431    0.594  167.898  audio_features   \n",
       "2          0.000000     0.374    0.564  146.870  audio_features   \n",
       "3          0.000000     0.353    0.444  166.071  audio_features   \n",
       "4          0.000247     0.256    0.370  112.021  audio_features   \n",
       "\n",
       "                       id                                   uri  \\\n",
       "0  1IthE5GNiRzFN5CVaCa445  spotify:track:1IthE5GNiRzFN5CVaCa445   \n",
       "1  27S8iOXD7Z58yvJtyk2S9j  spotify:track:27S8iOXD7Z58yvJtyk2S9j   \n",
       "2  2GEnvQgSJhedm2sqZlOP8o  spotify:track:2GEnvQgSJhedm2sqZlOP8o   \n",
       "3  0vMk4IrUfSJQkhwZnVX6us  spotify:track:0vMk4IrUfSJQkhwZnVX6us   \n",
       "4  0Q53fuiKLGjDKD7Mme7EoQ  spotify:track:0Q53fuiKLGjDKD7Mme7EoQ   \n",
       "\n",
       "                                          track_href  \\\n",
       "0  https://api.spotify.com/v1/tracks/1IthE5GNiRzF...   \n",
       "1  https://api.spotify.com/v1/tracks/27S8iOXD7Z58...   \n",
       "2  https://api.spotify.com/v1/tracks/2GEnvQgSJhed...   \n",
       "3  https://api.spotify.com/v1/tracks/0vMk4IrUfSJQ...   \n",
       "4  https://api.spotify.com/v1/tracks/0Q53fuiKLGjD...   \n",
       "\n",
       "                                        analysis_url  duration_ms  \\\n",
       "0  https://api.spotify.com/v1/audio-analysis/1Ith...       238628   \n",
       "1  https://api.spotify.com/v1/audio-analysis/27S8...       222067   \n",
       "2  https://api.spotify.com/v1/audio-analysis/2GEn...       209752   \n",
       "3  https://api.spotify.com/v1/audio-analysis/0vMk...       231384   \n",
       "4  https://api.spotify.com/v1/audio-analysis/0Q53...       245810   \n",
       "\n",
       "   time_signature  \n",
       "0               4  \n",
       "1               4  \n",
       "2               4  \n",
       "3               4  \n",
       "4               4  "
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Get audio features for the tracks\n",
    "track_ids = tracks_df['id']\n",
    "chunk_size = 50\n",
    "chunks = [track_ids[i:i + chunk_size] for i in range(0, len(track_ids), chunk_size)]\n",
    "\n",
    "# Initialize a list to store the audio features\n",
    "audio_features = []\n",
    "\n",
    "# Retrieve audio features for each chunk of track IDs\n",
    "for chunk in chunks:\n",
    "    audio_features_chunk = sp.audio_features(chunk)\n",
    "    audio_features.extend(audio_features_chunk)\n",
    "audio_features_df = pd.DataFrame(audio_features)  \n",
    "audio_features_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "bcf3d1a5-dd5c-4bad-a6a6-c49a4d9e6348",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>artists</th>\n",
       "      <th>available_markets</th>\n",
       "      <th>disc_number</th>\n",
       "      <th>duration_ms</th>\n",
       "      <th>explicit</th>\n",
       "      <th>external_urls</th>\n",
       "      <th>href</th>\n",
       "      <th>id</th>\n",
       "      <th>name</th>\n",
       "      <th>preview_url</th>\n",
       "      <th>...</th>\n",
       "      <th>instrumentalness</th>\n",
       "      <th>liveness</th>\n",
       "      <th>valence</th>\n",
       "      <th>tempo</th>\n",
       "      <th>type_audio</th>\n",
       "      <th>uri_audio</th>\n",
       "      <th>track_href</th>\n",
       "      <th>analysis_url</th>\n",
       "      <th>duration_ms_audio</th>\n",
       "      <th>time_signature</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>238628</td>\n",
       "      <td>False</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/1I...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/1IthE5GNiRzF...</td>\n",
       "      <td>1IthE5GNiRzFN5CVaCa445</td>\n",
       "      <td>Born Singer</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/ed6b39048436eed9...</td>\n",
       "      <td>...</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.235</td>\n",
       "      <td>0.684</td>\n",
       "      <td>157.937</td>\n",
       "      <td>audio_features</td>\n",
       "      <td>spotify:track:1IthE5GNiRzFN5CVaCa445</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/1IthE5GNiRzF...</td>\n",
       "      <td>https://api.spotify.com/v1/audio-analysis/1Ith...</td>\n",
       "      <td>238628</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>222066</td>\n",
       "      <td>False</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/27...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/27S8iOXD7Z58...</td>\n",
       "      <td>27S8iOXD7Z58yvJtyk2S9j</td>\n",
       "      <td>No More Dream</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/57660681261bd993...</td>\n",
       "      <td>...</td>\n",
       "      <td>0.000002</td>\n",
       "      <td>0.431</td>\n",
       "      <td>0.594</td>\n",
       "      <td>167.898</td>\n",
       "      <td>audio_features</td>\n",
       "      <td>spotify:track:27S8iOXD7Z58yvJtyk2S9j</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/27S8iOXD7Z58...</td>\n",
       "      <td>https://api.spotify.com/v1/audio-analysis/27S8...</td>\n",
       "      <td>222067</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>209751</td>\n",
       "      <td>False</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/2G...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/2GEnvQgSJhed...</td>\n",
       "      <td>2GEnvQgSJhedm2sqZlOP8o</td>\n",
       "      <td>N.O</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/fb5d285eb734057e...</td>\n",
       "      <td>...</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.374</td>\n",
       "      <td>0.564</td>\n",
       "      <td>146.870</td>\n",
       "      <td>audio_features</td>\n",
       "      <td>spotify:track:2GEnvQgSJhedm2sqZlOP8o</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/2GEnvQgSJhed...</td>\n",
       "      <td>https://api.spotify.com/v1/audio-analysis/2GEn...</td>\n",
       "      <td>209752</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>231384</td>\n",
       "      <td>False</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/0v...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/0vMk4IrUfSJQ...</td>\n",
       "      <td>0vMk4IrUfSJQkhwZnVX6us</td>\n",
       "      <td>Boy In Luv</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/fa7c36a5b5248d48...</td>\n",
       "      <td>...</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.353</td>\n",
       "      <td>0.444</td>\n",
       "      <td>166.071</td>\n",
       "      <td>audio_features</td>\n",
       "      <td>spotify:track:0vMk4IrUfSJQkhwZnVX6us</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/0vMk4IrUfSJQ...</td>\n",
       "      <td>https://api.spotify.com/v1/audio-analysis/0vMk...</td>\n",
       "      <td>231384</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>245810</td>\n",
       "      <td>False</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/0Q...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/0Q53fuiKLGjD...</td>\n",
       "      <td>0Q53fuiKLGjDKD7Mme7EoQ</td>\n",
       "      <td>Danger</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/93246e06867e64cc...</td>\n",
       "      <td>...</td>\n",
       "      <td>0.000247</td>\n",
       "      <td>0.256</td>\n",
       "      <td>0.370</td>\n",
       "      <td>112.021</td>\n",
       "      <td>audio_features</td>\n",
       "      <td>spotify:track:0Q53fuiKLGjDKD7Mme7EoQ</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/0Q53fuiKLGjD...</td>\n",
       "      <td>https://api.spotify.com/v1/audio-analysis/0Q53...</td>\n",
       "      <td>245810</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 31 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                             artists  \\\n",
       "0  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "1  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "2  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "3  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "4  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "\n",
       "                                   available_markets  disc_number  \\\n",
       "0  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "1  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "2  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "3  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "4  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "\n",
       "   duration_ms  explicit                                      external_urls  \\\n",
       "0       238628     False  {'spotify': 'https://open.spotify.com/track/1I...   \n",
       "1       222066     False  {'spotify': 'https://open.spotify.com/track/27...   \n",
       "2       209751     False  {'spotify': 'https://open.spotify.com/track/2G...   \n",
       "3       231384     False  {'spotify': 'https://open.spotify.com/track/0v...   \n",
       "4       245810     False  {'spotify': 'https://open.spotify.com/track/0Q...   \n",
       "\n",
       "                                                href                      id  \\\n",
       "0  https://api.spotify.com/v1/tracks/1IthE5GNiRzF...  1IthE5GNiRzFN5CVaCa445   \n",
       "1  https://api.spotify.com/v1/tracks/27S8iOXD7Z58...  27S8iOXD7Z58yvJtyk2S9j   \n",
       "2  https://api.spotify.com/v1/tracks/2GEnvQgSJhed...  2GEnvQgSJhedm2sqZlOP8o   \n",
       "3  https://api.spotify.com/v1/tracks/0vMk4IrUfSJQ...  0vMk4IrUfSJQkhwZnVX6us   \n",
       "4  https://api.spotify.com/v1/tracks/0Q53fuiKLGjD...  0Q53fuiKLGjDKD7Mme7EoQ   \n",
       "\n",
       "            name                                        preview_url  ...  \\\n",
       "0    Born Singer  https://p.scdn.co/mp3-preview/ed6b39048436eed9...  ...   \n",
       "1  No More Dream  https://p.scdn.co/mp3-preview/57660681261bd993...  ...   \n",
       "2            N.O  https://p.scdn.co/mp3-preview/fb5d285eb734057e...  ...   \n",
       "3     Boy In Luv  https://p.scdn.co/mp3-preview/fa7c36a5b5248d48...  ...   \n",
       "4         Danger  https://p.scdn.co/mp3-preview/93246e06867e64cc...  ...   \n",
       "\n",
       "   instrumentalness liveness valence    tempo      type_audio  \\\n",
       "0          0.000000    0.235   0.684  157.937  audio_features   \n",
       "1          0.000002    0.431   0.594  167.898  audio_features   \n",
       "2          0.000000    0.374   0.564  146.870  audio_features   \n",
       "3          0.000000    0.353   0.444  166.071  audio_features   \n",
       "4          0.000247    0.256   0.370  112.021  audio_features   \n",
       "\n",
       "                              uri_audio  \\\n",
       "0  spotify:track:1IthE5GNiRzFN5CVaCa445   \n",
       "1  spotify:track:27S8iOXD7Z58yvJtyk2S9j   \n",
       "2  spotify:track:2GEnvQgSJhedm2sqZlOP8o   \n",
       "3  spotify:track:0vMk4IrUfSJQkhwZnVX6us   \n",
       "4  spotify:track:0Q53fuiKLGjDKD7Mme7EoQ   \n",
       "\n",
       "                                          track_href  \\\n",
       "0  https://api.spotify.com/v1/tracks/1IthE5GNiRzF...   \n",
       "1  https://api.spotify.com/v1/tracks/27S8iOXD7Z58...   \n",
       "2  https://api.spotify.com/v1/tracks/2GEnvQgSJhed...   \n",
       "3  https://api.spotify.com/v1/tracks/0vMk4IrUfSJQ...   \n",
       "4  https://api.spotify.com/v1/tracks/0Q53fuiKLGjD...   \n",
       "\n",
       "                                        analysis_url  duration_ms_audio  \\\n",
       "0  https://api.spotify.com/v1/audio-analysis/1Ith...             238628   \n",
       "1  https://api.spotify.com/v1/audio-analysis/27S8...             222067   \n",
       "2  https://api.spotify.com/v1/audio-analysis/2GEn...             209752   \n",
       "3  https://api.spotify.com/v1/audio-analysis/0vMk...             231384   \n",
       "4  https://api.spotify.com/v1/audio-analysis/0Q53...             245810   \n",
       "\n",
       "   time_signature  \n",
       "0               4  \n",
       "1               4  \n",
       "2               4  \n",
       "3               4  \n",
       "4               4  \n",
       "\n",
       "[5 rows x 31 columns]"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Combine track data with audio features\n",
    "merged_df = tracks_df.merge(audio_features_df, left_on='id', right_on='id', suffixes=('', '_audio'))\n",
    "merged_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "95383f24-d229-48ba-9c8f-ee6b470d1b9d",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>name</th>\n",
       "      <th>id</th>\n",
       "      <th>danceability</th>\n",
       "      <th>energy</th>\n",
       "      <th>key</th>\n",
       "      <th>loudness</th>\n",
       "      <th>speechiness</th>\n",
       "      <th>acousticness</th>\n",
       "      <th>instrumentalness</th>\n",
       "      <th>liveness</th>\n",
       "      <th>valence</th>\n",
       "      <th>tempo</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Born Singer</td>\n",
       "      <td>1IthE5GNiRzFN5CVaCa445</td>\n",
       "      <td>0.602</td>\n",
       "      <td>0.841</td>\n",
       "      <td>8</td>\n",
       "      <td>-3.334</td>\n",
       "      <td>0.109</td>\n",
       "      <td>0.035400</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.235</td>\n",
       "      <td>0.684</td>\n",
       "      <td>157.937</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>No More Dream</td>\n",
       "      <td>27S8iOXD7Z58yvJtyk2S9j</td>\n",
       "      <td>0.438</td>\n",
       "      <td>0.864</td>\n",
       "      <td>2</td>\n",
       "      <td>-5.185</td>\n",
       "      <td>0.470</td>\n",
       "      <td>0.011800</td>\n",
       "      <td>0.000002</td>\n",
       "      <td>0.431</td>\n",
       "      <td>0.594</td>\n",
       "      <td>167.898</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>N.O</td>\n",
       "      <td>2GEnvQgSJhedm2sqZlOP8o</td>\n",
       "      <td>0.597</td>\n",
       "      <td>0.909</td>\n",
       "      <td>11</td>\n",
       "      <td>-4.500</td>\n",
       "      <td>0.160</td>\n",
       "      <td>0.044300</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.374</td>\n",
       "      <td>0.564</td>\n",
       "      <td>146.870</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Boy In Luv</td>\n",
       "      <td>0vMk4IrUfSJQkhwZnVX6us</td>\n",
       "      <td>0.492</td>\n",
       "      <td>0.931</td>\n",
       "      <td>9</td>\n",
       "      <td>-3.837</td>\n",
       "      <td>0.297</td>\n",
       "      <td>0.002440</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.353</td>\n",
       "      <td>0.444</td>\n",
       "      <td>166.071</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Danger</td>\n",
       "      <td>0Q53fuiKLGjDKD7Mme7EoQ</td>\n",
       "      <td>0.734</td>\n",
       "      <td>0.848</td>\n",
       "      <td>1</td>\n",
       "      <td>-4.433</td>\n",
       "      <td>0.102</td>\n",
       "      <td>0.000913</td>\n",
       "      <td>0.000247</td>\n",
       "      <td>0.256</td>\n",
       "      <td>0.370</td>\n",
       "      <td>112.021</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "            name                      id  danceability  energy  key  loudness  \\\n",
       "0    Born Singer  1IthE5GNiRzFN5CVaCa445         0.602   0.841    8    -3.334   \n",
       "1  No More Dream  27S8iOXD7Z58yvJtyk2S9j         0.438   0.864    2    -5.185   \n",
       "2            N.O  2GEnvQgSJhedm2sqZlOP8o         0.597   0.909   11    -4.500   \n",
       "3     Boy In Luv  0vMk4IrUfSJQkhwZnVX6us         0.492   0.931    9    -3.837   \n",
       "4         Danger  0Q53fuiKLGjDKD7Mme7EoQ         0.734   0.848    1    -4.433   \n",
       "\n",
       "   speechiness  acousticness  instrumentalness  liveness  valence    tempo  \n",
       "0        0.109      0.035400          0.000000     0.235    0.684  157.937  \n",
       "1        0.470      0.011800          0.000002     0.431    0.594  167.898  \n",
       "2        0.160      0.044300          0.000000     0.374    0.564  146.870  \n",
       "3        0.297      0.002440          0.000000     0.353    0.444  166.071  \n",
       "4        0.102      0.000913          0.000247     0.256    0.370  112.021  "
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    " # Perform recommendation logic (example: find similar tracks)\n",
    "recommendation_df = merged_df[['name','id', 'danceability', 'energy', 'key', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo']]\n",
    "recommendation_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7668107b-76f0-4216-a37c-5f51f5d7d308",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "2d5b8a73-c400-42d6-a306-254cfbcf1e56",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>href</th>\n",
       "      <th>id</th>\n",
       "      <th>icons</th>\n",
       "      <th>name</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>https://api.spotify.com/v1/browse/categories/0...</td>\n",
       "      <td>0JQ5DAt0tbjZptfcdMSKl3</td>\n",
       "      <td>[{'height': 274, 'url': 'https://t.scdn.co/ima...</td>\n",
       "      <td>Made For You</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>https://api.spotify.com/v1/browse/categories/0...</td>\n",
       "      <td>0JQ5DAqbMKFz6FAsUtgAab</td>\n",
       "      <td>[{'height': 274, 'url': 'https://t.scdn.co/ima...</td>\n",
       "      <td>New Releases</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>https://api.spotify.com/v1/browse/categories/0...</td>\n",
       "      <td>0JQ5DAqbMKFHCxg5H5PtqW</td>\n",
       "      <td>[{'height': 274, 'url': 'https://t.scdn.co/ima...</td>\n",
       "      <td>Hindi</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>https://api.spotify.com/v1/browse/categories/0...</td>\n",
       "      <td>0JQ5DAqbMKFKSopHMaeIeI</td>\n",
       "      <td>[{'height': 274, 'url': 'https://t.scdn.co/ima...</td>\n",
       "      <td>Punjabi</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>https://api.spotify.com/v1/browse/categories/0...</td>\n",
       "      <td>0JQ5DAqbMKFE33XAyDiPIr</td>\n",
       "      <td>[{'height': 274, 'url': 'https://t.scdn.co/ima...</td>\n",
       "      <td>Tamil</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                href                      id  \\\n",
       "0  https://api.spotify.com/v1/browse/categories/0...  0JQ5DAt0tbjZptfcdMSKl3   \n",
       "1  https://api.spotify.com/v1/browse/categories/0...  0JQ5DAqbMKFz6FAsUtgAab   \n",
       "2  https://api.spotify.com/v1/browse/categories/0...  0JQ5DAqbMKFHCxg5H5PtqW   \n",
       "3  https://api.spotify.com/v1/browse/categories/0...  0JQ5DAqbMKFKSopHMaeIeI   \n",
       "4  https://api.spotify.com/v1/browse/categories/0...  0JQ5DAqbMKFE33XAyDiPIr   \n",
       "\n",
       "                                               icons          name  \n",
       "0  [{'height': 274, 'url': 'https://t.scdn.co/ima...  Made For You  \n",
       "1  [{'height': 274, 'url': 'https://t.scdn.co/ima...  New Releases  \n",
       "2  [{'height': 274, 'url': 'https://t.scdn.co/ima...         Hindi  \n",
       "3  [{'height': 274, 'url': 'https://t.scdn.co/ima...       Punjabi  \n",
       "4  [{'height': 274, 'url': 'https://t.scdn.co/ima...         Tamil  "
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cat =sp.categories(country=None, locale=None, limit=50, offset=0)\n",
    "cat_df=pd.DataFrame(cat['categories']['items'])\n",
    "cat_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "db407dfd-b918-46ed-92ec-63979d34f330",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "def rec(song):\n",
    "    song = song.lower()\n",
    "    recommendation_df['name'] = recommendation_df['name'].str.lower()\n",
    "    x = recommendation_df.drop('name',axis=1)\n",
    "    x = x.drop('id',axis=1)\n",
    "    matrix = x\n",
    "    similarity = cosine_similarity(matrix)\n",
    "    print(\"Looking for song like:\", song)\n",
    "    \n",
    "    matching_rows = recommendation_df[recommendation_df['name'].str.contains(song)]\n",
    "    \n",
    "    if matching_rows.empty:\n",
    "        print(\"Song not found.\")\n",
    "        return\n",
    "    \n",
    "    idx = matching_rows.index[0]\n",
    "    distances = sorted(list(enumerate(similarity[idx])), reverse=True, key=lambda x:x[1]) \n",
    "    \n",
    "    songs = []\n",
    "    for m_id in distances[1:11]:\n",
    "        songs.append(recommendation_df.loc[m_id[0],'name'])\n",
    "    recommendations=[]\n",
    "    for x in songs:\n",
    "        # check if exists in unique_list or not\n",
    "        if x not in recommendations:\n",
    "            recommendations.append(x)\n",
    "    \n",
    "    return recommendations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "70c28e6c-cb35-47e8-9641-339be54b53f3",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter a song you like: love myself\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Looking for song like: love myself\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "['dna',\n",
       " 'bts cypher 4',\n",
       " 'trivia 起 : just dance',\n",
       " 'black swan',\n",
       " 'danger',\n",
       " 'fake love - japanese ver.']"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "song=input(\"Enter a song you like:\")\n",
    "rec(song)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f17c2754-0bc2-44bb-a23d-cdd6f31a2cd8",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "ea37579e-dbcd-40fa-a9d9-4e315ee63749",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'2X3UgVLSA4wYriGIQyYmMA'"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "matching_rows = recommendation_df[recommendation_df['name'].str.contains(song)]\n",
    "track_id = str(matching_rows.iloc[0]['id'])\n",
    "track_id"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "d53d5188-3b9f-4cc6-ac50-7018ed7014d9",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "recc=sp.recommendations(seed_artists=[artist_id],seed_tracks=[track_id])\n",
    "recc_df=pd.DataFrame(recc['tracks'])\n",
    "recc_df=recc_df.sort_values(by=\"popularity\",ascending=False)\n",
    "recc_df=recc_df.reset_index(drop=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "6f978e0a-a2f4-43ae-baa9-17eca3fd1fa2",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['Wild Flower (with youjeen)',\n",
       " 'That That (prod.&feat. SUGA of BTS)',\n",
       " 'LILAC',\n",
       " 'Beautiful',\n",
       " 'La Vie en Rose',\n",
       " 'Blueming',\n",
       " 'Dionysus',\n",
       " 'DUN DUN',\n",
       " 'LATATA',\n",
       " 'Paradise',\n",
       " 'SMILEY(Feat. BIBI)',\n",
       " \"I'm Not Cool\",\n",
       " 'Strawberry Cake',\n",
       " \"Pandora's Box\",\n",
       " 'TAIL',\n",
       " 'Traffic light',\n",
       " 'Heartstrings',\n",
       " '9 and Three Quarters (Run Away)',\n",
       " 'Then, Now and Forever',\n",
       " 'Return (With Yuk Jidam)']"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "song_names=recc_df['name'].tolist()\n",
    "song_names"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "5f75a0ef-05eb-4fb8-bf38-6e7131ad4d9b",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>album</th>\n",
       "      <th>artists</th>\n",
       "      <th>available_markets</th>\n",
       "      <th>disc_number</th>\n",
       "      <th>duration_ms</th>\n",
       "      <th>explicit</th>\n",
       "      <th>external_ids</th>\n",
       "      <th>external_urls</th>\n",
       "      <th>href</th>\n",
       "      <th>id</th>\n",
       "      <th>is_local</th>\n",
       "      <th>is_playable</th>\n",
       "      <th>name</th>\n",
       "      <th>popularity</th>\n",
       "      <th>preview_url</th>\n",
       "      <th>track_number</th>\n",
       "      <th>type</th>\n",
       "      <th>uri</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>{'album_type': 'album', 'artists': [{'external...</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>154486</td>\n",
       "      <td>False</td>\n",
       "      <td>{'isrc': 'USAT22205563'}</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/5O...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/5Odq8ohlgIbQ...</td>\n",
       "      <td>5Odq8ohlgIbQKMZivbWkEo</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>Left and Right (Feat. Jung Kook of BTS)</td>\n",
       "      <td>80</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/9e4342eefa4f33df...</td>\n",
       "      <td>6</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:5Odq8ohlgIbQKMZivbWkEo</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>{'album_type': 'album', 'artists': [{'external...</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>199053</td>\n",
       "      <td>False</td>\n",
       "      <td>{'isrc': 'QM7282022872'}</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/5Q...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/5QDLhrAOJJdN...</td>\n",
       "      <td>5QDLhrAOJJdNAmCTJ8xMyW</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>Dynamite</td>\n",
       "      <td>79</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/98e266fea9df84fa...</td>\n",
       "      <td>8</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:5QDLhrAOJJdNAmCTJ8xMyW</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>{'album_type': 'album', 'artists': [{'external...</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>226198</td>\n",
       "      <td>False</td>\n",
       "      <td>{'isrc': 'GBAYE2100952'}</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/46...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/46HNZY1i7O6j...</td>\n",
       "      <td>46HNZY1i7O6jwTA7Slo2PI</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>My Universe</td>\n",
       "      <td>76</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/0790eb03d0d2b6aa...</td>\n",
       "      <td>10</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:46HNZY1i7O6jwTA7Slo2PI</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>{'album_type': 'album', 'artists': [{'external...</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>242333</td>\n",
       "      <td>False</td>\n",
       "      <td>{'isrc': 'QM4TX1817912'}</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/6m...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/6m1TWFMeon7a...</td>\n",
       "      <td>6m1TWFMeon7ai9XLOzdbiR</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>FAKE LOVE</td>\n",
       "      <td>75</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/24ec465728ed83e2...</td>\n",
       "      <td>2</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:6m1TWFMeon7ai9XLOzdbiR</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>{'album_type': 'album', 'artists': [{'external...</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>164952</td>\n",
       "      <td>False</td>\n",
       "      <td>{'isrc': 'QM6MZ2156864'}</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/6j...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/6jjYDGxVJsWS...</td>\n",
       "      <td>6jjYDGxVJsWS0a5wlVF5vS</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>Butter</td>\n",
       "      <td>74</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/4d63fe1638aa4159...</td>\n",
       "      <td>18</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:6jjYDGxVJsWS0a5wlVF5vS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>{'album_type': 'album', 'artists': [{'external...</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>229773</td>\n",
       "      <td>False</td>\n",
       "      <td>{'isrc': 'QM6MZ1917908'}</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/4a...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/4a9tbd947vo9...</td>\n",
       "      <td>4a9tbd947vo9K8Vti9JwcI</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>Boy With Luv (feat. Halsey)</td>\n",
       "      <td>74</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/c5e4b03bcf18d2b1...</td>\n",
       "      <td>2</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:4a9tbd947vo9K8Vti9JwcI</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>{'album_type': 'album', 'artists': [{'external...</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>2</td>\n",
       "      <td>204939</td>\n",
       "      <td>False</td>\n",
       "      <td>{'isrc': 'USA2P2226298'}</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/69...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/69xohKu8C1fs...</td>\n",
       "      <td>69xohKu8C1fsflYAiSNbwM</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>Run BTS</td>\n",
       "      <td>75</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/abc4f797c5378fe6...</td>\n",
       "      <td>1</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:69xohKu8C1fsflYAiSNbwM</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>{'album_type': 'album', 'artists': [{'external...</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>207481</td>\n",
       "      <td>False</td>\n",
       "      <td>{'isrc': 'QMBZ92051791'}</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/5F...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/5FVbvttjEvQ8...</td>\n",
       "      <td>5FVbvttjEvQ8r2BgUcJgNg</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>Life Goes On</td>\n",
       "      <td>74</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/fd53b34cdf00c5cb...</td>\n",
       "      <td>1</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:5FVbvttjEvQ8r2BgUcJgNg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>{'album_type': 'album', 'artists': [{'external...</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>274097</td>\n",
       "      <td>False</td>\n",
       "      <td>{'isrc': 'KRA381700253'}</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/2j...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/2j1fFjWHCI9K...</td>\n",
       "      <td>2j1fFjWHCI9KJSwcuYAOyF</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>Spring Day</td>\n",
       "      <td>73</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/e2504a289eb9462a...</td>\n",
       "      <td>15</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:2j1fFjWHCI9KJSwcuYAOyF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>{'album_type': 'single', 'artists': [{'externa...</td>\n",
       "      <td>[{'external_urls': {'spotify': 'https://open.s...</td>\n",
       "      <td>[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...</td>\n",
       "      <td>1</td>\n",
       "      <td>187585</td>\n",
       "      <td>False</td>\n",
       "      <td>{'isrc': 'QMFME2102684'}</td>\n",
       "      <td>{'spotify': 'https://open.spotify.com/track/3X...</td>\n",
       "      <td>https://api.spotify.com/v1/tracks/3XYRV7ZSHqIR...</td>\n",
       "      <td>3XYRV7ZSHqIRDG87DKTtry</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>Permission to Dance</td>\n",
       "      <td>73</td>\n",
       "      <td>https://p.scdn.co/mp3-preview/d4eb140d131417cc...</td>\n",
       "      <td>1</td>\n",
       "      <td>track</td>\n",
       "      <td>spotify:track:3XYRV7ZSHqIRDG87DKTtry</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                               album  \\\n",
       "0  {'album_type': 'album', 'artists': [{'external...   \n",
       "1  {'album_type': 'album', 'artists': [{'external...   \n",
       "2  {'album_type': 'album', 'artists': [{'external...   \n",
       "3  {'album_type': 'album', 'artists': [{'external...   \n",
       "4  {'album_type': 'album', 'artists': [{'external...   \n",
       "5  {'album_type': 'album', 'artists': [{'external...   \n",
       "6  {'album_type': 'album', 'artists': [{'external...   \n",
       "7  {'album_type': 'album', 'artists': [{'external...   \n",
       "8  {'album_type': 'album', 'artists': [{'external...   \n",
       "9  {'album_type': 'single', 'artists': [{'externa...   \n",
       "\n",
       "                                             artists  \\\n",
       "0  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "1  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "2  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "3  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "4  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "5  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "6  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "7  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "8  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "9  [{'external_urls': {'spotify': 'https://open.s...   \n",
       "\n",
       "                                   available_markets  disc_number  \\\n",
       "0  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "1  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "2  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "3  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "4  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "5  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "6  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            2   \n",
       "7  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "8  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "9  [AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...            1   \n",
       "\n",
       "   duration_ms  explicit              external_ids  \\\n",
       "0       154486     False  {'isrc': 'USAT22205563'}   \n",
       "1       199053     False  {'isrc': 'QM7282022872'}   \n",
       "2       226198     False  {'isrc': 'GBAYE2100952'}   \n",
       "3       242333     False  {'isrc': 'QM4TX1817912'}   \n",
       "4       164952     False  {'isrc': 'QM6MZ2156864'}   \n",
       "5       229773     False  {'isrc': 'QM6MZ1917908'}   \n",
       "6       204939     False  {'isrc': 'USA2P2226298'}   \n",
       "7       207481     False  {'isrc': 'QMBZ92051791'}   \n",
       "8       274097     False  {'isrc': 'KRA381700253'}   \n",
       "9       187585     False  {'isrc': 'QMFME2102684'}   \n",
       "\n",
       "                                       external_urls  \\\n",
       "0  {'spotify': 'https://open.spotify.com/track/5O...   \n",
       "1  {'spotify': 'https://open.spotify.com/track/5Q...   \n",
       "2  {'spotify': 'https://open.spotify.com/track/46...   \n",
       "3  {'spotify': 'https://open.spotify.com/track/6m...   \n",
       "4  {'spotify': 'https://open.spotify.com/track/6j...   \n",
       "5  {'spotify': 'https://open.spotify.com/track/4a...   \n",
       "6  {'spotify': 'https://open.spotify.com/track/69...   \n",
       "7  {'spotify': 'https://open.spotify.com/track/5F...   \n",
       "8  {'spotify': 'https://open.spotify.com/track/2j...   \n",
       "9  {'spotify': 'https://open.spotify.com/track/3X...   \n",
       "\n",
       "                                                href                      id  \\\n",
       "0  https://api.spotify.com/v1/tracks/5Odq8ohlgIbQ...  5Odq8ohlgIbQKMZivbWkEo   \n",
       "1  https://api.spotify.com/v1/tracks/5QDLhrAOJJdN...  5QDLhrAOJJdNAmCTJ8xMyW   \n",
       "2  https://api.spotify.com/v1/tracks/46HNZY1i7O6j...  46HNZY1i7O6jwTA7Slo2PI   \n",
       "3  https://api.spotify.com/v1/tracks/6m1TWFMeon7a...  6m1TWFMeon7ai9XLOzdbiR   \n",
       "4  https://api.spotify.com/v1/tracks/6jjYDGxVJsWS...  6jjYDGxVJsWS0a5wlVF5vS   \n",
       "5  https://api.spotify.com/v1/tracks/4a9tbd947vo9...  4a9tbd947vo9K8Vti9JwcI   \n",
       "6  https://api.spotify.com/v1/tracks/69xohKu8C1fs...  69xohKu8C1fsflYAiSNbwM   \n",
       "7  https://api.spotify.com/v1/tracks/5FVbvttjEvQ8...  5FVbvttjEvQ8r2BgUcJgNg   \n",
       "8  https://api.spotify.com/v1/tracks/2j1fFjWHCI9K...  2j1fFjWHCI9KJSwcuYAOyF   \n",
       "9  https://api.spotify.com/v1/tracks/3XYRV7ZSHqIR...  3XYRV7ZSHqIRDG87DKTtry   \n",
       "\n",
       "   is_local  is_playable                                     name  popularity  \\\n",
       "0     False         True  Left and Right (Feat. Jung Kook of BTS)          80   \n",
       "1     False         True                                 Dynamite          79   \n",
       "2     False         True                              My Universe          76   \n",
       "3     False         True                                FAKE LOVE          75   \n",
       "4     False         True                                   Butter          74   \n",
       "5     False         True              Boy With Luv (feat. Halsey)          74   \n",
       "6     False         True                                  Run BTS          75   \n",
       "7     False         True                             Life Goes On          74   \n",
       "8     False         True                               Spring Day          73   \n",
       "9     False         True                      Permission to Dance          73   \n",
       "\n",
       "                                         preview_url  track_number   type  \\\n",
       "0  https://p.scdn.co/mp3-preview/9e4342eefa4f33df...             6  track   \n",
       "1  https://p.scdn.co/mp3-preview/98e266fea9df84fa...             8  track   \n",
       "2  https://p.scdn.co/mp3-preview/0790eb03d0d2b6aa...            10  track   \n",
       "3  https://p.scdn.co/mp3-preview/24ec465728ed83e2...             2  track   \n",
       "4  https://p.scdn.co/mp3-preview/4d63fe1638aa4159...            18  track   \n",
       "5  https://p.scdn.co/mp3-preview/c5e4b03bcf18d2b1...             2  track   \n",
       "6  https://p.scdn.co/mp3-preview/abc4f797c5378fe6...             1  track   \n",
       "7  https://p.scdn.co/mp3-preview/fd53b34cdf00c5cb...             1  track   \n",
       "8  https://p.scdn.co/mp3-preview/e2504a289eb9462a...            15  track   \n",
       "9  https://p.scdn.co/mp3-preview/d4eb140d131417cc...             1  track   \n",
       "\n",
       "                                    uri  \n",
       "0  spotify:track:5Odq8ohlgIbQKMZivbWkEo  \n",
       "1  spotify:track:5QDLhrAOJJdNAmCTJ8xMyW  \n",
       "2  spotify:track:46HNZY1i7O6jwTA7Slo2PI  \n",
       "3  spotify:track:6m1TWFMeon7ai9XLOzdbiR  \n",
       "4  spotify:track:6jjYDGxVJsWS0a5wlVF5vS  \n",
       "5  spotify:track:4a9tbd947vo9K8Vti9JwcI  \n",
       "6  spotify:track:69xohKu8C1fsflYAiSNbwM  \n",
       "7  spotify:track:5FVbvttjEvQ8r2BgUcJgNg  \n",
       "8  spotify:track:2j1fFjWHCI9KJSwcuYAOyF  \n",
       "9  spotify:track:3XYRV7ZSHqIRDG87DKTtry  "
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "top10=sp.artist_top_tracks(artist_id)\n",
    "top10_df=pd.DataFrame(top10['tracks'])\n",
    "top10_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "7d62e055-c0f9-43d6-8541-5dee203a349b",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['Left and Right (Feat. Jung Kook of BTS)',\n",
       " 'Dynamite',\n",
       " 'My Universe',\n",
       " 'FAKE LOVE',\n",
       " 'Butter',\n",
       " 'Boy With Luv (feat. Halsey)',\n",
       " 'Run BTS',\n",
       " 'Life Goes On',\n",
       " 'Spring Day',\n",
       " 'Permission to Dance']"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "song_name=top10_df['name'].tolist()\n",
    "song_name"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6695d718-6aa2-4a67-866f-605636acc7f8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b082364b-2b14-4a33-8dd5-21a5652d9702",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a0c209aa-d482-4efe-a40f-4942a8f76ccb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
